import { db } from "./db";
import { radicals } from "@shared/schema";

// Complete list of 214 Kangxi radicals
const radicalsData = [
  { index: 1, traditional: "一", simplified: "一", pinyin: "yī", numberedPinyin: "yi1" },
  { index: 2, traditional: "丨", simplified: "丨", pinyin: "shù", numberedPinyin: "shu4" },
  { index: 3, traditional: "丶", simplified: "丶", pinyin: "diǎn", numberedPinyin: "dian3" },
  { index: 4, traditional: "丿", simplified: "丿", pinyin: "piě", numberedPinyin: "pie3" },
  { index: 5, traditional: "乙", simplified: "乙", pinyin: "yǐ", numberedPinyin: "yi3" },
  { index: 6, traditional: "亅", simplified: "亅", pinyin: "gōu", numberedPinyin: "gou1" },
  { index: 7, traditional: "二", simplified: "二", pinyin: "èr", numberedPinyin: "er4" },
  { index: 8, traditional: "亠", simplified: "亠", pinyin: "tóu", numberedPinyin: "tou2" },
  { index: 9, traditional: "人", simplified: "人", pinyin: "rén", numberedPinyin: "ren2" },
  { index: 10, traditional: "儿", simplified: "儿", pinyin: "ér", numberedPinyin: "er2" },
  { index: 11, traditional: "入", simplified: "入", pinyin: "rù", numberedPinyin: "ru4" },
  { index: 12, traditional: "八", simplified: "八", pinyin: "bā", numberedPinyin: "ba1" },
  { index: 13, traditional: "冂", simplified: "冂", pinyin: "jiǒng", numberedPinyin: "jiong3" },
  { index: 14, traditional: "冖", simplified: "冖", pinyin: "mì", numberedPinyin: "mi4" },
  { index: 15, traditional: "冫", simplified: "冫", pinyin: "bīng", numberedPinyin: "bing1" },
  { index: 16, traditional: "几", simplified: "几", pinyin: "jī", numberedPinyin: "ji1" },
  { index: 17, traditional: "凵", simplified: "凵", pinyin: "qǔ", numberedPinyin: "qu3" },
  { index: 18, traditional: "刀", simplified: "刀", pinyin: "dāo", numberedPinyin: "dao1" },
  { index: 19, traditional: "力", simplified: "力", pinyin: "lì", numberedPinyin: "li4" },
  { index: 20, traditional: "勹", simplified: "勹", pinyin: "bāo", numberedPinyin: "bao1" },
  { index: 21, traditional: "匕", simplified: "匕", pinyin: "bǐ", numberedPinyin: "bi3" },
  { index: 22, traditional: "匚", simplified: "匚", pinyin: "fāng", numberedPinyin: "fang1" },
  { index: 23, traditional: "匸", simplified: "匸", pinyin: "xǐ", numberedPinyin: "xi3" },
  { index: 24, traditional: "十", simplified: "十", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 25, traditional: "卜", simplified: "卜", pinyin: "bǔ", numberedPinyin: "bu3" },
  { index: 26, traditional: "卩", simplified: "卩", pinyin: "jié", numberedPinyin: "jie2" },
  { index: 27, traditional: "厂", simplified: "厂", pinyin: "hàn", numberedPinyin: "han4" },
  { index: 28, traditional: "厶", simplified: "厶", pinyin: "sī", numberedPinyin: "si1" },
  { index: 29, traditional: "又", simplified: "又", pinyin: "yòu", numberedPinyin: "you4" },
  { index: 30, traditional: "口", simplified: "口", pinyin: "kǒu", numberedPinyin: "kou3" },
  { index: 31, traditional: "囗", simplified: "囗", pinyin: "wéi", numberedPinyin: "wei2" },
  { index: 32, traditional: "土", simplified: "土", pinyin: "tǔ", numberedPinyin: "tu3" },
  { index: 33, traditional: "士", simplified: "士", pinyin: "shì", numberedPinyin: "shi4" },
  { index: 34, traditional: "夂", simplified: "夂", pinyin: "zhī", numberedPinyin: "zhi1" },
  { index: 35, traditional: "夊", simplified: "夊", pinyin: "suī", numberedPinyin: "sui1" },
  { index: 36, traditional: "夕", simplified: "夕", pinyin: "xī", numberedPinyin: "xi1" },
  { index: 37, traditional: "大", simplified: "大", pinyin: "dà", numberedPinyin: "da4" },
  { index: 38, traditional: "女", simplified: "女", pinyin: "nǚ", numberedPinyin: "nv3" },
  { index: 39, traditional: "子", simplified: "子", pinyin: "zǐ", numberedPinyin: "zi3" },
  { index: 40, traditional: "宀", simplified: "宀", pinyin: "miánzi", numberedPinyin: "mianzi" },
  { index: 41, traditional: "寸", simplified: "寸", pinyin: "cùn", numberedPinyin: "cun4" },
  { index: 42, traditional: "小", simplified: "小", pinyin: "xiǎo", numberedPinyin: "xiao3" },
  { index: 43, traditional: "尢", simplified: "尢", pinyin: "yóu", numberedPinyin: "you2" },
  { index: 44, traditional: "尸", simplified: "尸", pinyin: "shī", numberedPinyin: "shi1" },
  { index: 45, traditional: "屮", simplified: "屮", pinyin: "chè", numberedPinyin: "che4" },
  { index: 46, traditional: "山", simplified: "山", pinyin: "shān", numberedPinyin: "shan1" },
  { index: 47, traditional: "川", simplified: "川", pinyin: "chuān", numberedPinyin: "chuan1" },
  { index: 48, traditional: "工", simplified: "工", pinyin: "gōng", numberedPinyin: "gong1" },
  { index: 49, traditional: "己", simplified: "己", pinyin: "jǐ", numberedPinyin: "ji3" },
  { index: 50, traditional: "巾", simplified: "巾", pinyin: "jīn", numberedPinyin: "jin1" },
  { index: 51, traditional: "干", simplified: "干", pinyin: "gān", numberedPinyin: "gan1" },
  { index: 52, traditional: "幺", simplified: "幺", pinyin: "yāo", numberedPinyin: "yao1" },
  { index: 53, traditional: "广", simplified: "广", pinyin: "guǎng", numberedPinyin: "guang3" },
  { index: 54, traditional: "廴", simplified: "廴", pinyin: "yǐn", numberedPinyin: "yin3" },
  { index: 55, traditional: "廾", simplified: "廾", pinyin: "gǒng", numberedPinyin: "gong3" },
  { index: 56, traditional: "弋", simplified: "弋", pinyin: "yì", numberedPinyin: "yi4" },
  { index: 57, traditional: "弓", simplified: "弓", pinyin: "gōng", numberedPinyin: "gong1" },
  { index: 58, traditional: "彐", simplified: "彐", pinyin: "jì", numberedPinyin: "ji4" },
  { index: 59, traditional: "彡", simplified: "彡", pinyin: "shān", numberedPinyin: "shan1" },
  { index: 60, traditional: "彳", simplified: "彳", pinyin: "chì", numberedPinyin: "chi4" },
  { index: 61, traditional: "心", simplified: "心", pinyin: "xīn", numberedPinyin: "xin1" },
  { index: 62, traditional: "戈", simplified: "戈", pinyin: "gē", numberedPinyin: "ge1" },
  { index: 63, traditional: "户", simplified: "户", pinyin: "hù", numberedPinyin: "hu4" },
  { index: 64, traditional: "手", simplified: "手", pinyin: "shǒu", numberedPinyin: "shou3" },
  { index: 65, traditional: "支", simplified: "支", pinyin: "zhī", numberedPinyin: "zhi1" },
  { index: 66, traditional: "攴", simplified: "攴", pinyin: "pū", numberedPinyin: "pu1" },
  { index: 67, traditional: "文", simplified: "文", pinyin: "wén", numberedPinyin: "wen2" },
  { index: 68, traditional: "斗", simplified: "斗", pinyin: "dǒu", numberedPinyin: "dou3" },
  { index: 69, traditional: "斤", simplified: "斤", pinyin: "jīn", numberedPinyin: "jin1" },
  { index: 70, traditional: "方", simplified: "方", pinyin: "fāng", numberedPinyin: "fang1" },
  { index: 71, traditional: "无", simplified: "无", pinyin: "wú", numberedPinyin: "wu2" },
  { index: 72, traditional: "日", simplified: "日", pinyin: "rì", numberedPinyin: "ri4" },
  { index: 73, traditional: "曰", simplified: "曰", pinyin: "yuē", numberedPinyin: "yue1" },
  { index: 74, traditional: "月", simplified: "月", pinyin: "yuè", numberedPinyin: "yue4" },
  { index: 75, traditional: "木", simplified: "木", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 76, traditional: "欠", simplified: "欠", pinyin: "qiàn", numberedPinyin: "qian4" },
  { index: 77, traditional: "止", simplified: "止", pinyin: "zhǐ", numberedPinyin: "zhi3" },
  { index: 78, traditional: "歹", simplified: "歹", pinyin: "dǎi", numberedPinyin: "dai3" },
  { index: 79, traditional: "殳", simplified: "殳", pinyin: "shū", numberedPinyin: "shu1" },
  { index: 80, traditional: "母", simplified: "母", pinyin: "mǔ", numberedPinyin: "mu3" },
  { index: 81, traditional: "比", simplified: "比", pinyin: "bǐ", numberedPinyin: "bi3" },
  { index: 82, traditional: "毛", simplified: "毛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 83, traditional: "氏", simplified: "氏", pinyin: "shì", numberedPinyin: "shi4" },
  { index: 84, traditional: "气", simplified: "气", pinyin: "qì", numberedPinyin: "qi4" },
  { index: 85, traditional: "水", simplified: "水", pinyin: "shuǐ", numberedPinyin: "shui3" },
  { index: 86, traditional: "火", simplified: "火", pinyin: "huǒ", numberedPinyin: "huo3" },
  { index: 87, traditional: "爪", simplified: "爪", pinyin: "zhǎo", numberedPinyin: "zhao3" },
  { index: 88, traditional: "父", simplified: "父", pinyin: "fù", numberedPinyin: "fu4" },
  { index: 89, traditional: "爻", simplified: "爻", pinyin: "yáo", numberedPinyin: "yao2" },
  { index: 90, traditional: "爿", simplified: "爿", pinyin: "qiáng", numberedPinyin: "qiang2" },
  { index: 91, traditional: "片", simplified: "片", pinyin: "piàn", numberedPinyin: "pian4" },
  { index: 92, traditional: "牙", simplified: "牙", pinyin: "yá", numberedPinyin: "ya2" },
  { index: 93, traditional: "牛", simplified: "牛", pinyin: "niú", numberedPinyin: "niu2" },
  { index: 94, traditional: "犭", simplified: "犭", pinyin: "quǎn", numberedPinyin: "quan3" },
  { index: 95, traditional: "玄", simplified: "玄", pinyin: "xuán", numberedPinyin: "xuan2" },
  { index: 96, traditional: "玉", simplified: "玉", pinyin: "yù", numberedPinyin: "yu4" },
  { index: 97, traditional: "瓜", simplified: "瓜", pinyin: "guā", numberedPinyin: "gua1" },
  { index: 98, traditional: "瓦", simplified: "瓦", pinyin: "wǎ", numberedPinyin: "wa3" },
  { index: 99, traditional: "甘", simplified: "甘", pinyin: "gān", numberedPinyin: "gan1" },
  { index: 100, traditional: "生", simplified: "生", pinyin: "shēng", numberedPinyin: "sheng1" },
  { index: 101, traditional: "用", simplified: "用", pinyin: "yòng", numberedPinyin: "yong4" },
  { index: 102, traditional: "田", simplified: "田", pinyin: "tián", numberedPinyin: "tian2" },
  { index: 103, traditional: "疋", simplified: "疋", pinyin: "pǐ", numberedPinyin: "pi3" },
  { index: 104, traditional: "疒", simplified: "疒", pinyin: "bìng", numberedPinyin: "bing4" },
  { index: 105, traditional: "癶", simplified: "癶", pinyin: "bō", numberedPinyin: "bo1" },
  { index: 106, traditional: "白", simplified: "白", pinyin: "bái", numberedPinyin: "bai2" },
  { index: 107, traditional: "皮", simplified: "皮", pinyin: "pí", numberedPinyin: "pi2" },
  { index: 108, traditional: "皿", simplified: "皿", pinyin: "mǐn", numberedPinyin: "min3" },
  { index: 109, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 110, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 111, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 112, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 113, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 114, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 115, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 116, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 117, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 118, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 119, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 120, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 121, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 122, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 123, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 124, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 125, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 126, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 127, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 128, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 129, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 130, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 131, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 132, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 133, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 134, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 135, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 136, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 137, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 138, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 139, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 140, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 141, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 142, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 143, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 144, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 145, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 146, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 147, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 148, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 149, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 150, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 151, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 152, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 153, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 154, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 155, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 156, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 157, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 158, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 159, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 160, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 161, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 162, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 163, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 164, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 165, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 166, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 167, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 168, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 169, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 170, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 171, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 172, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 173, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 174, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 175, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 176, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 177, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 178, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 179, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 180, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 181, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 182, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 183, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 184, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 185, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 186, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 187, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 188, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 189, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 190, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 191, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 192, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 193, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 194, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 195, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 196, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 197, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 198, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 199, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 200, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 201, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 202, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 203, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 204, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 205, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 206, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 207, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 208, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 209, traditional: "业", simplified: "业", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 210, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 211, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 212, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 213, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 214, traditional: "龙", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
];

async function seedRadicals() {
  try {
    console.log("Starting to seed radicals...");
    
    // Delete existing radicals
    await db.delete(radicals);
    
    // Insert new radicals
    for (const radical of radicalsData) {
      await db.insert(radicals).values({
        index: radical.index,
        traditional: radical.traditional,
        simplified: radical.simplified,
        pinyin: radical.pinyin,
        numberedPinyin: radical.numberedPinyin,
        alternativeFormIndex: null,
        mainIndex: 1,
      }).onConflictDoNothing();
    }
    
    console.log(`Successfully seeded ${radicalsData.length} radicals`);
    process.exit(0);
  } catch (error) {
    console.error("Error seeding radicals:", error);
    process.exit(1);
  }
}

seedRadicals();
