import { db } from "./db";
import { radicals } from "@shared/schema";

const radicalsData = [
  { index: 1, traditional: "一", simplified: "一", pinyin: "yī", numberedPinyin: "yi1" },
  { index: 2, traditional: "丨", simplified: "丨", pinyin: "shù", numberedPinyin: "shu4" },
  { index: 3, traditional: "丶", simplified: "丶", pinyin: "diǎn", numberedPinyin: "dian3" },
  { index: 4, traditional: "丿", simplified: "丿", pinyin: "piě", numberedPinyin: "pie3" },
  { index: 5, traditional: "乙", simplified: "乙", pinyin: "yǐ", numberedPinyin: "yi3" },
  { index: 6, traditional: "亅", simplified: "亅", pinyin: "gōu", numberedPinyin: "gou1" },
  { index: 7, traditional: "二", simplified: "二", pinyin: "èr", numberedPinyin: "er4" },
  { index: 8, traditional: "亠", simplified: "亠", pinyin: "tóu", numberedPinyin: "tou2" },
  { index: 9, traditional: "人", simplified: "人", pinyin: "rén", numberedPinyin: "ren2" },
  { index: 10, traditional: "儿", simplified: "儿", pinyin: "ér", numberedPinyin: "er2" },
  { index: 11, traditional: "入", simplified: "入", pinyin: "rù", numberedPinyin: "ru4" },
  { index: 12, traditional: "八", simplified: "八", pinyin: "bā", numberedPinyin: "ba1" },
  { index: 13, traditional: "冂", simplified: "冂", pinyin: "jiǒng", numberedPinyin: "jiong3" },
  { index: 14, traditional: "冖", simplified: "冖", pinyin: "mì", numberedPinyin: "mi4" },
  { index: 15, traditional: "冫", simplified: "冫", pinyin: "bīng", numberedPinyin: "bing1" },
  { index: 16, traditional: "几", simplified: "几", pinyin: "jī", numberedPinyin: "ji1" },
  { index: 17, traditional: "凵", simplified: "凵", pinyin: "qǔ", numberedPinyin: "qu3" },
  { index: 18, traditional: "刀", simplified: "刀", pinyin: "dāo", numberedPinyin: "dao1" },
  { index: 19, traditional: "力", simplified: "力", pinyin: "lì", numberedPinyin: "li4" },
  { index: 20, traditional: "勹", simplified: "勹", pinyin: "bāo", numberedPinyin: "bao1" },
  { index: 21, traditional: "匕", simplified: "匕", pinyin: "bǐ", numberedPinyin: "bi3" },
  { index: 22, traditional: "匚", simplified: "匚", pinyin: "fāng", numberedPinyin: "fang1" },
  { index: 23, traditional: "匸", simplified: "匸", pinyin: "xǐ", numberedPinyin: "xi3" },
  { index: 24, traditional: "十", simplified: "十", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 25, traditional: "卜", simplified: "卜", pinyin: "bǔ", numberedPinyin: "bu3" },
  { index: 26, traditional: "卩", simplified: "卩", pinyin: "jié", numberedPinyin: "jie2" },
  { index: 27, traditional: "厂", simplified: "厂", pinyin: "hàn", numberedPinyin: "han4" },
  { index: 28, traditional: "厶", simplified: "厶", pinyin: "sī", numberedPinyin: "si1" },
  { index: 29, traditional: "又", simplified: "又", pinyin: "yòu", numberedPinyin: "you4" },
  { index: 30, traditional: "口", simplified: "口", pinyin: "kǒu", numberedPinyin: "kou3" },
  { index: 31, traditional: "囗", simplified: "囗", pinyin: "wéi", numberedPinyin: "wei2" },
  { index: 32, traditional: "土", simplified: "土", pinyin: "tǔ", numberedPinyin: "tu3" },
  { index: 33, traditional: "士", simplified: "士", pinyin: "shì", numberedPinyin: "shi4" },
  { index: 34, traditional: "夂", simplified: "夂", pinyin: "zhī", numberedPinyin: "zhi1" },
  { index: 35, traditional: "夊", simplified: "夊", pinyin: "suī", numberedPinyin: "sui1" },
  { index: 36, traditional: "夕", simplified: "夕", pinyin: "xī", numberedPinyin: "xi1" },
  { index: 37, traditional: "大", simplified: "大", pinyin: "dà", numberedPinyin: "da4" },
  { index: 38, traditional: "女", simplified: "女", pinyin: "nǚ", numberedPinyin: "nv3" },
  { index: 39, traditional: "子", simplified: "子", pinyin: "zǐ", numberedPinyin: "zi3" },
  { index: 40, traditional: "宀", simplified: "宀", pinyin: "mián", numberedPinyin: "mian2" },
  { index: 41, traditional: "寸", simplified: "寸", pinyin: "cùn", numberedPinyin: "cun4" },
  { index: 42, traditional: "小", simplified: "小", pinyin: "xiǎo", numberedPinyin: "xiao3" },
  { index: 43, traditional: "尢", simplified: "尢", pinyin: "wāng", numberedPinyin: "wang1" },
  { index: 44, traditional: "尸", simplified: "尸", pinyin: "shī", numberedPinyin: "shi1" },
  { index: 45, traditional: "屮", simplified: "屮", pinyin: "chè", numberedPinyin: "che4" },
  { index: 46, traditional: "山", simplified: "山", pinyin: "shān", numberedPinyin: "shan1" },
  { index: 47, traditional: "巛", simplified: "川", pinyin: "chuān", numberedPinyin: "chuan1" },
  { index: 48, traditional: "工", simplified: "工", pinyin: "gōng", numberedPinyin: "gong1" },
  { index: 49, traditional: "己", simplified: "己", pinyin: "jǐ", numberedPinyin: "ji3" },
  { index: 50, traditional: "巾", simplified: "巾", pinyin: "jīn", numberedPinyin: "jin1" },
  { index: 51, traditional: "干", simplified: "干", pinyin: "gān", numberedPinyin: "gan1" },
  { index: 52, traditional: "幺", simplified: "幺", pinyin: "yāo", numberedPinyin: "yao1" },
  { index: 53, traditional: "广", simplified: "广", pinyin: "guǎng", numberedPinyin: "guang3" },
  { index: 54, traditional: "廴", simplified: "廴", pinyin: "yǐn", numberedPinyin: "yin3" },
  { index: 55, traditional: "廾", simplified: "廾", pinyin: "gǒng", numberedPinyin: "gong3" },
  { index: 56, traditional: "弋", simplified: "弋", pinyin: "yì", numberedPinyin: "yi4" },
  { index: 57, traditional: "弓", simplified: "弓", pinyin: "gōng", numberedPinyin: "gong1" },
  { index: 58, traditional: "彐", simplified: "彐", pinyin: "jì", numberedPinyin: "ji4" },
  { index: 59, traditional: "彡", simplified: "彡", pinyin: "shān", numberedPinyin: "shan1" },
  { index: 60, traditional: "彳", simplified: "彳", pinyin: "chì", numberedPinyin: "chi4" },
  { index: 61, traditional: "心", simplified: "心", pinyin: "xīn", numberedPinyin: "xin1" },
  { index: 62, traditional: "戈", simplified: "戈", pinyin: "gē", numberedPinyin: "ge1" },
  { index: 63, traditional: "戶", simplified: "户", pinyin: "hù", numberedPinyin: "hu4" },
  { index: 64, traditional: "手", simplified: "手", pinyin: "shǒu", numberedPinyin: "shou3" },
  { index: 65, traditional: "支", simplified: "支", pinyin: "zhī", numberedPinyin: "zhi1" },
  { index: 66, traditional: "攴", simplified: "攴", pinyin: "pū", numberedPinyin: "pu1" },
  { index: 67, traditional: "文", simplified: "文", pinyin: "wén", numberedPinyin: "wen2" },
  { index: 68, traditional: "斗", simplified: "斗", pinyin: "dǒu", numberedPinyin: "dou3" },
  { index: 69, traditional: "斤", simplified: "斤", pinyin: "jīn", numberedPinyin: "jin1" },
  { index: 70, traditional: "方", simplified: "方", pinyin: "fāng", numberedPinyin: "fang1" },
  { index: 71, traditional: "无", simplified: "无", pinyin: "wú", numberedPinyin: "wu2" },
  { index: 72, traditional: "日", simplified: "日", pinyin: "rì", numberedPinyin: "ri4" },
  { index: 73, traditional: "曰", simplified: "曰", pinyin: "yuē", numberedPinyin: "yue1" },
  { index: 74, traditional: "月", simplified: "月", pinyin: "yuè", numberedPinyin: "yue4" },
  { index: 75, traditional: "木", simplified: "木", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 76, traditional: "欠", simplified: "欠", pinyin: "qiàn", numberedPinyin: "qian4" },
  { index: 77, traditional: "止", simplified: "止", pinyin: "zhǐ", numberedPinyin: "zhi3" },
  { index: 78, traditional: "歹", simplified: "歹", pinyin: "dǎi", numberedPinyin: "dai3" },
  { index: 79, traditional: "殳", simplified: "殳", pinyin: "shū", numberedPinyin: "shu1" },
  { index: 80, traditional: "毋", simplified: "毋", pinyin: "wú", numberedPinyin: "wu2" },
  { index: 81, traditional: "比", simplified: "比", pinyin: "bǐ", numberedPinyin: "bi3" },
  { index: 82, traditional: "毛", simplified: "毛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 83, traditional: "氏", simplified: "氏", pinyin: "shì", numberedPinyin: "shi4" },
  { index: 84, traditional: "气", simplified: "气", pinyin: "qì", numberedPinyin: "qi4" },
  { index: 85, traditional: "水", simplified: "水", pinyin: "shuǐ", numberedPinyin: "shui3" },
  { index: 86, traditional: "火", simplified: "火", pinyin: "huǒ", numberedPinyin: "huo3" },
  { index: 87, traditional: "爪", simplified: "爪", pinyin: "zhǎo", numberedPinyin: "zhao3" },
  { index: 88, traditional: "父", simplified: "父", pinyin: "fù", numberedPinyin: "fu4" },
  { index: 89, traditional: "爻", simplified: "爻", pinyin: "yáo", numberedPinyin: "yao2" },
  { index: 90, traditional: "爿", simplified: "爿", pinyin: "pán", numberedPinyin: "pan2" },
  { index: 91, traditional: "片", simplified: "片", pinyin: "piàn", numberedPinyin: "pian4" },
  { index: 92, traditional: "牙", simplified: "牙", pinyin: "yá", numberedPinyin: "ya2" },
  { index: 93, traditional: "牛", simplified: "牛", pinyin: "niú", numberedPinyin: "niu2" },
  { index: 94, traditional: "犬", simplified: "犬", pinyin: "quǎn", numberedPinyin: "quan3" },
  { index: 95, traditional: "玄", simplified: "玄", pinyin: "xuán", numberedPinyin: "xuan2" },
  { index: 96, traditional: "玉", simplified: "玉", pinyin: "yù", numberedPinyin: "yu4" },
  { index: 97, traditional: "瓜", simplified: "瓜", pinyin: "guā", numberedPinyin: "gua1" },
  { index: 98, traditional: "瓦", simplified: "瓦", pinyin: "wǎ", numberedPinyin: "wa3" },
  { index: 99, traditional: "甘", simplified: "甘", pinyin: "gān", numberedPinyin: "gan1" },
  { index: 100, traditional: "生", simplified: "生", pinyin: "shēng", numberedPinyin: "sheng1" },
  { index: 101, traditional: "用", simplified: "用", pinyin: "yòng", numberedPinyin: "yong4" },
  { index: 102, traditional: "田", simplified: "田", pinyin: "tián", numberedPinyin: "tian2" },
  { index: 103, traditional: "疋", simplified: "疋", pinyin: "pǐ", numberedPinyin: "pi3" },
  { index: 104, traditional: "疒", simplified: "疒", pinyin: "nè", numberedPinyin: "ne4" },
  { index: 105, traditional: "癶", simplified: "癶", pinyin: "bō", numberedPinyin: "bo1" },
  { index: 106, traditional: "白", simplified: "白", pinyin: "bái", numberedPinyin: "bai2" },
  { index: 107, traditional: "皮", simplified: "皮", pinyin: "pí", numberedPinyin: "pi2" },
  { index: 108, traditional: "皿", simplified: "皿", pinyin: "mǐn", numberedPinyin: "min3" },
  { index: 109, traditional: "目", simplified: "目", pinyin: "mù", numberedPinyin: "mu4" },
  { index: 110, traditional: "矛", simplified: "矛", pinyin: "máo", numberedPinyin: "mao2" },
  { index: 111, traditional: "矢", simplified: "矢", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 112, traditional: "石", simplified: "石", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 113, traditional: "示", simplified: "示", pinyin: "shì", numberedPinyin: "shi4" },
  { index: 114, traditional: "禸", simplified: "禸", pinyin: "róu", numberedPinyin: "rou2" },
  { index: 115, traditional: "禾", simplified: "禾", pinyin: "hé", numberedPinyin: "he2" },
  { index: 116, traditional: "穴", simplified: "穴", pinyin: "xué", numberedPinyin: "xue2" },
  { index: 117, traditional: "立", simplified: "立", pinyin: "lì", numberedPinyin: "li4" },
  { index: 118, traditional: "竹", simplified: "竹", pinyin: "zhú", numberedPinyin: "zhu2" },
  { index: 119, traditional: "米", simplified: "米", pinyin: "mǐ", numberedPinyin: "mi3" },
  { index: 120, traditional: "糸", simplified: "糸", pinyin: "mì", numberedPinyin: "mi4" },
  { index: 121, traditional: "缶", simplified: "缶", pinyin: "fǒu", numberedPinyin: "fou3" },
  { index: 122, traditional: "网", simplified: "网", pinyin: "wǎng", numberedPinyin: "wang3" },
  { index: 123, traditional: "羊", simplified: "羊", pinyin: "yáng", numberedPinyin: "yang2" },
  { index: 124, traditional: "羽", simplified: "羽", pinyin: "yǔ", numberedPinyin: "yu3" },
  { index: 125, traditional: "老", simplified: "老", pinyin: "lǎo", numberedPinyin: "lao3" },
  { index: 126, traditional: "而", simplified: "而", pinyin: "ér", numberedPinyin: "er2" },
  { index: 127, traditional: "耒", simplified: "耒", pinyin: "lěi", numberedPinyin: "lei3" },
  { index: 128, traditional: "耳", simplified: "耳", pinyin: "ěr", numberedPinyin: "er3" },
  { index: 129, traditional: "聿", simplified: "聿", pinyin: "yù", numberedPinyin: "yu4" },
  { index: 130, traditional: "肉", simplified: "肉", pinyin: "ròu", numberedPinyin: "rou4" },
  { index: 131, traditional: "臣", simplified: "臣", pinyin: "chén", numberedPinyin: "chen2" },
  { index: 132, traditional: "自", simplified: "自", pinyin: "zì", numberedPinyin: "zi4" },
  { index: 133, traditional: "至", simplified: "至", pinyin: "zhì", numberedPinyin: "zhi4" },
  { index: 134, traditional: "臼", simplified: "臼", pinyin: "jiù", numberedPinyin: "jiu4" },
  { index: 135, traditional: "舌", simplified: "舌", pinyin: "shé", numberedPinyin: "she2" },
  { index: 136, traditional: "舛", simplified: "舛", pinyin: "chuǎn", numberedPinyin: "chuan3" },
  { index: 137, traditional: "舟", simplified: "舟", pinyin: "zhōu", numberedPinyin: "zhou1" },
  { index: 138, traditional: "艮", simplified: "艮", pinyin: "gèn", numberedPinyin: "gen4" },
  { index: 139, traditional: "色", simplified: "色", pinyin: "sè", numberedPinyin: "se4" },
  { index: 140, traditional: "艸", simplified: "艹", pinyin: "cǎo", numberedPinyin: "cao3" },
  { index: 141, traditional: "虍", simplified: "虍", pinyin: "hū", numberedPinyin: "hu1" },
  { index: 142, traditional: "虫", simplified: "虫", pinyin: "chóng", numberedPinyin: "chong2" },
  { index: 143, traditional: "血", simplified: "血", pinyin: "xuè", numberedPinyin: "xue4" },
  { index: 144, traditional: "行", simplified: "行", pinyin: "xíng", numberedPinyin: "xing2" },
  { index: 145, traditional: "衣", simplified: "衣", pinyin: "yī", numberedPinyin: "yi1" },
  { index: 146, traditional: "襾", simplified: "西", pinyin: "xī", numberedPinyin: "xi1" },
  { index: 147, traditional: "見", simplified: "见", pinyin: "jiàn", numberedPinyin: "jian4" },
  { index: 148, traditional: "角", simplified: "角", pinyin: "jiǎo", numberedPinyin: "jiao3" },
  { index: 149, traditional: "言", simplified: "言", pinyin: "yán", numberedPinyin: "yan2" },
  { index: 150, traditional: "谷", simplified: "谷", pinyin: "gǔ", numberedPinyin: "gu3" },
  { index: 151, traditional: "豆", simplified: "豆", pinyin: "dòu", numberedPinyin: "dou4" },
  { index: 152, traditional: "豕", simplified: "豕", pinyin: "shǐ", numberedPinyin: "shi3" },
  { index: 153, traditional: "豸", simplified: "豸", pinyin: "zhì", numberedPinyin: "zhi4" },
  { index: 154, traditional: "貝", simplified: "贝", pinyin: "bèi", numberedPinyin: "bei4" },
  { index: 155, traditional: "赤", simplified: "赤", pinyin: "chì", numberedPinyin: "chi4" },
  { index: 156, traditional: "走", simplified: "走", pinyin: "zǒu", numberedPinyin: "zou3" },
  { index: 157, traditional: "足", simplified: "足", pinyin: "zú", numberedPinyin: "zu2" },
  { index: 158, traditional: "身", simplified: "身", pinyin: "shēn", numberedPinyin: "shen1" },
  { index: 159, traditional: "車", simplified: "车", pinyin: "chē", numberedPinyin: "che1" },
  { index: 160, traditional: "辛", simplified: "辛", pinyin: "xīn", numberedPinyin: "xin1" },
  { index: 161, traditional: "辰", simplified: "辰", pinyin: "chén", numberedPinyin: "chen2" },
  { index: 162, traditional: "辵", simplified: "辶", pinyin: "chuò", numberedPinyin: "chuo4" },
  { index: 163, traditional: "邑", simplified: "邑", pinyin: "yì", numberedPinyin: "yi4" },
  { index: 164, traditional: "酉", simplified: "酉", pinyin: "yǒu", numberedPinyin: "you3" },
  { index: 165, traditional: "釆", simplified: "釆", pinyin: "biàn", numberedPinyin: "bian4" },
  { index: 166, traditional: "里", simplified: "里", pinyin: "lǐ", numberedPinyin: "li3" },
  { index: 167, traditional: "金", simplified: "金", pinyin: "jīn", numberedPinyin: "jin1" },
  { index: 168, traditional: "長", simplified: "长", pinyin: "cháng", numberedPinyin: "chang2" },
  { index: 169, traditional: "門", simplified: "门", pinyin: "mén", numberedPinyin: "men2" },
  { index: 170, traditional: "阜", simplified: "阜", pinyin: "fù", numberedPinyin: "fu4" },
  { index: 171, traditional: "隶", simplified: "隶", pinyin: "lì", numberedPinyin: "li4" },
  { index: 172, traditional: "隹", simplified: "隹", pinyin: "zhuī", numberedPinyin: "zhui1" },
  { index: 173, traditional: "雨", simplified: "雨", pinyin: "yǔ", numberedPinyin: "yu3" },
  { index: 174, traditional: "靑", simplified: "青", pinyin: "qīng", numberedPinyin: "qing1" },
  { index: 175, traditional: "非", simplified: "非", pinyin: "fēi", numberedPinyin: "fei1" },
  { index: 176, traditional: "面", simplified: "面", pinyin: "miàn", numberedPinyin: "mian4" },
  { index: 177, traditional: "革", simplified: "革", pinyin: "gé", numberedPinyin: "ge2" },
  { index: 178, traditional: "韋", simplified: "韦", pinyin: "wéi", numberedPinyin: "wei2" },
  { index: 179, traditional: "韭", simplified: "韭", pinyin: "jiǔ", numberedPinyin: "jiu3" },
  { index: 180, traditional: "音", simplified: "音", pinyin: "yīn", numberedPinyin: "yin1" },
  { index: 181, traditional: "頁", simplified: "页", pinyin: "yè", numberedPinyin: "ye4" },
  { index: 182, traditional: "風", simplified: "风", pinyin: "fēng", numberedPinyin: "feng1" },
  { index: 183, traditional: "飛", simplified: "飞", pinyin: "fēi", numberedPinyin: "fei1" },
  { index: 184, traditional: "食", simplified: "食", pinyin: "shí", numberedPinyin: "shi2" },
  { index: 185, traditional: "首", simplified: "首", pinyin: "shǒu", numberedPinyin: "shou3" },
  { index: 186, traditional: "香", simplified: "香", pinyin: "xiāng", numberedPinyin: "xiang1" },
  { index: 187, traditional: "馬", simplified: "马", pinyin: "mǎ", numberedPinyin: "ma3" },
  { index: 188, traditional: "骨", simplified: "骨", pinyin: "gǔ", numberedPinyin: "gu3" },
  { index: 189, traditional: "高", simplified: "高", pinyin: "gāo", numberedPinyin: "gao1" },
  { index: 190, traditional: "髟", simplified: "髟", pinyin: "biāo", numberedPinyin: "biao1" },
  { index: 191, traditional: "鬥", simplified: "斗", pinyin: "dòu", numberedPinyin: "dou4" },
  { index: 192, traditional: "鬯", simplified: "鬯", pinyin: "chàng", numberedPinyin: "chang4" },
  { index: 193, traditional: "鬲", simplified: "鬲", pinyin: "lì", numberedPinyin: "li4" },
  { index: 194, traditional: "鬼", simplified: "鬼", pinyin: "guǐ", numberedPinyin: "gui3" },
  { index: 195, traditional: "魚", simplified: "鱼", pinyin: "yú", numberedPinyin: "yu2" },
  { index: 196, traditional: "鳥", simplified: "鸟", pinyin: "niǎo", numberedPinyin: "niao3" },
  { index: 197, traditional: "鹵", simplified: "卤", pinyin: "lǔ", numberedPinyin: "lu3" },
  { index: 198, traditional: "鹿", simplified: "鹿", pinyin: "lù", numberedPinyin: "lu4" },
  { index: 199, traditional: "麥", simplified: "麦", pinyin: "mài", numberedPinyin: "mai4" },
  { index: 200, traditional: "麻", simplified: "麻", pinyin: "má", numberedPinyin: "ma2" },
  { index: 201, traditional: "黃", simplified: "黄", pinyin: "huáng", numberedPinyin: "huang2" },
  { index: 202, traditional: "黍", simplified: "黍", pinyin: "shǔ", numberedPinyin: "shu3" },
  { index: 203, traditional: "黑", simplified: "黑", pinyin: "hēi", numberedPinyin: "hei1" },
  { index: 204, traditional: "黹", simplified: "黹", pinyin: "zhǐ", numberedPinyin: "zhi3" },
  { index: 205, traditional: "黽", simplified: "黾", pinyin: "mǐn", numberedPinyin: "min3" },
  { index: 206, traditional: "鼎", simplified: "鼎", pinyin: "dǐng", numberedPinyin: "ding3" },
  { index: 207, traditional: "鼓", simplified: "鼓", pinyin: "gǔ", numberedPinyin: "gu3" },
  { index: 208, traditional: "鼠", simplified: "鼠", pinyin: "shǔ", numberedPinyin: "shu3" },
  { index: 209, traditional: "鼻", simplified: "鼻", pinyin: "bí", numberedPinyin: "bi2" },
  { index: 210, traditional: "齊", simplified: "齐", pinyin: "qí", numberedPinyin: "qi2" },
  { index: 211, traditional: "齒", simplified: "齿", pinyin: "chǐ", numberedPinyin: "chi3" },
  { index: 212, traditional: "龍", simplified: "龙", pinyin: "lóng", numberedPinyin: "long2" },
  { index: 213, traditional: "龜", simplified: "龟", pinyin: "guī", numberedPinyin: "gui1" },
  { index: 214, traditional: "龠", simplified: "龠", pinyin: "yuè", numberedPinyin: "yue4" },
];

async function seedRadicals() {
  try {
    console.log("Starting to seed radicals...");
    
    await db.delete(radicals);
    
    for (const radical of radicalsData) {
      await db.insert(radicals).values({
        index: radical.index,
        traditional: radical.traditional,
        simplified: radical.simplified,
        pinyin: radical.pinyin,
        numberedPinyin: radical.numberedPinyin,
        alternativeFormIndex: null,
        mainIndex: 1,
      }).onConflictDoNothing();
    }
    
    console.log(`Successfully seeded ${radicalsData.length} radicals`);
    process.exit(0);
  } catch (error) {
    console.error("Error seeding radicals:", error);
    process.exit(1);
  }
}

seedRadicals();
